### ISSUE TITLE
Metadata.csv Line 306 -- 'No Finding' isn't correct

### ISSUE THREAD

**Issue by ArkanEmre** [ieee8023/covid-chestxray-dataset#112]
As described in the [radiopedia case](https://radiopaedia.org/cases/covid-19-pneumonia-58?lang=us,CC), the patient was testes positive for COVID-19 on two nasopharyngeal swab tests. Therefore, the finding should be COVID-19.

**Comment by ieee8023** [comment]
The first X-ray of the patient (the only one labelled as No Finding) is a prior image used as reference so they were not positive at that time.

I did fix the "went_icu" field for this patient because they were intubated so they must have been in the ICU.

Thanks for checking these fields! We need to keep reviewing them to make sure they are all correct!
