### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by fcakyon** [ieee8023/covid-chestxray-dataset#6]
Hello,

First of all thanks a lot for the effort you are putting to gather all these xray and ct measurements!

I am wondering if bounding box/masks for the detection of problematic regions can be provided or is this only available as an image classification dataset? If second, are there going to be also negative samples (xray images from covid-negative patients)?

Bests

**Comment by ieee8023** [comment]
> I am wondering if bounding box/masks for the detection of problematic regions can be provided or is this only available as an image classification dataset?

Bounding box/masks would be great to have. It should be easy to annotate the existing images. I would opt for a binary mask specifying the regions which are predictive. I'll add it to the list of things people can contribute.

> If second, are there going to be also negative samples (xray images from covid-negative patients)?

I've also been adding bacterial (Streptococcus) and other viral pneumonia cases (MERS).

For building models we have been using the other pneumonia datasets with pneumonia labels: NIH, CheXpert, Kaggle, PADCHEST (discussed here: https://arxiv.org/abs/2002.02497) with the assumption that none of those are caused by COVID-19.
